
local set = vim.keymap.set

set("v", "Y", '"+y')
set("v", ">", ">gv")
set("v", "<", "<gv")
set({"n", "x" }, "x", '"_x')
set({"n", "x" }, "X", '"_X')
set({"n", "x" }, "c", '"_c')
set({"n", "x" }, "C", '"_C')
set("x", "<leader>p", "\"_dp")
set("n", "<leader>E", ":Lexplore<CR>")
set("n", "<C-c>", ":terminal<CR>")
set("n", "<leader>F", ":find ")
set("n", "<Tab>", "gvo<Esc>")
set("n", "<C-d>", "<C-d>zz")
set("n", "<C-f>", "<C-f>zz")
set("n", "<C-u>", "<C-u>zz")
set("n", "n", "nzzzv")
set("n", "N", "Nzzzv")
set("n", "<A-j>", ":m .+1<CR>==", { noremap = true, silent = true })
set("n", "<A-k>", ":m .-2<CR>==", { noremap = true, silent = true })
set("v", "<A-j>", ":m '>+1<CR>gv=gv", { noremap = true, silent = true })
set("v", "<A-k>", ":m '<-2<CR>gv=gv", { noremap = true, silent = true })
set("n", "<C-h>", "<C-w>h", { noremap = true, silent = true })
set("n", "<A-h>", "<C-w>h", { noremap = true, silent = true })
set("n", "<C-j>", "<C-w>j", { noremap = true, silent = true })
set("n", "<C-k>", "<C-w>k", { noremap = true, silent = true })
set("n", "<A-l>", "<C-w>l", { noremap = true, silent = true })
set("n", "<C-l>", "<C-w>l", { noremap = true, silent = true })
set("n", "<A-,>", "<Cmd>BufferPrevious<CR>")
set("n", "<A-.>", "<Cmd>BufferNext<CR>")
set("n", "<A-1>", "<Cmd>BufferGoto 1<CR>")
set("n", "<A-2>", "<Cmd>BufferGoto 2<CR>")
set("n", "<A-3>", "<Cmd>BufferGoto 3<CR>")
set("n", "<A-4>", "<Cmd>BufferGoto 4<CR>")
set("n", "<A-5>", "<Cmd>BufferGoto 5<CR>")
set("n", "<C-1>", "<Cmd>BufferGoto 1<CR>")
set("n", "<C-2>", "<Cmd>BufferGoto 2<CR>")
set("n", "<C-3>", "<Cmd>BufferGoto 3<CR>")
set("n", "<C-4>", "<Cmd>BufferGoto 4<CR>")
set("n", "<C-5>", "<Cmd>BufferGoto 5<CR>")
set("n", "<A-c>", "<Cmd>BufferClose<CR>")
set("n", "<A-<>", "<Cmd>BufferMovePrevious<CR>")
set("n", "<A->>", "<Cmd>BufferMoveNext<CR>")
set("n", "<A-p>", "<Cmd>BufferPick<CR>")
set("n", "<A-b>", "<Cmd>BufferPickDelete<CR>")
