
vim.keymap.set("v", "Y", '"+y')
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", "Y", "\"+y")
vim.keymap.set("v", "<C-p>", "\"+p")
vim.keymap.set("v", "<leader>p", "\"_dp")
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv", { noremap = true, silent = true })
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv", { noremap = true, silent = true })
vim.keymap.set("x", "<leader>p", "\"_dp")
vim.keymap.set("n", "<leader>p", "\"_dp")
vim.keymap.set("n", "<C-p>", "\"+p")
vim.keymap.set("n", "<C-t>", ":terminal<CR>i")
vim.keymap.set("n", "<Tab>", "gvo<Esc>")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-f>", "<C-f>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-w>", ":w<CR>")
vim.keymap.set("n", "<C-s>", ":source ~/.config/nvim/init.lua<CR>")
vim.keymap.set("n", "<C-g>", ":w<CR>:!g++ % -o main<CR>")
vim.keymap.set("n", "<C-Q>", ":restart<CR>")
vim.keymap.set("n", "Q", ":BufferClose<CR>")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==", { noremap = true, silent = true })
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==", { noremap = true, silent = true })
vim.keymap.set("n", "Ff", [[:w<CR>:call system('Pdf- ' . shellescape(expand('%:p')))<CR>]], {noremap = true, silent = true})
vim.keymap.set("n", "FF", [[:w<CR>:call system('Pdf+ ' . shellescape(expand('%:p')))<CR>]], {noremap = true, silent = true})
vim.keymap.set("n", "ff", ":Telescope fd<CR>")
vim.keymap.set("n", "fF", ":Telescope find_files<CR>")
vim.keymap.set("n", "fs", ":Telescope live_grep<CR>")
vim.keymap.set("n", "fh", ":Telescope resume<CR>")
vim.keymap.set("n", "fd", ":Telescope buffers<CR>")
vim.keymap.set("n", "<leader>u", ":Telescope undo<CR>", { desc = "Undo history" })
vim.keymap.set("n", "<leader>fh", ":Telescope keymaps<CR>")
vim.keymap.set("n", "<leader>ff", ":Telescope<CR>")
