vim.keymap.set("v", "Y", '"+y')
vim.keymap.set("v", ">", ">gv")
vim.keymap.set("v", "<", "<gv")
vim.keymap.set("v", "Y", "\"+y")
vim.keymap.set("v", "<C-p>", "\"+p")
vim.keymap.set("v", "<leader>p", "\"_dp")
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "<leader>p", "\"_dp")
vim.keymap.set("n", "<C-Tab>", ":bnext<CR>")
vim.keymap.set("n", "<C-S-Tab>", ":bprevious<CR>")
vim.keymap.set("n", "<leader>p", "\"_dp")
vim.keymap.set("n", "<C-p>", "\"+p")
vim.keymap.set("n", "_", ":Oil<CR>")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-f>", "<C-f>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-w>", ":w<CR>")
vim.keymap.set("n", "<C-s>", ":source ~/.config/nvim/init.lua<CR>")
vim.keymap.set("n", "<C-Q>", ":%bdelete! | restart<CR>")
vim.keymap.set("n", "Q", ":bdelete!<CR>")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("n", "<C-w>", "<C-W>")
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==")
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==")
vim.keymap.set("n", "FF", ":w | LspTexlabBuild<CR>", { silent = true }, { desc = "Compiling" })
vim.keymap.set("n", "FJ", ":VimtexTocOpen<CR>", { silent = true }, { desc = "Talbe of Content" })
vim.keymap.set("n", "FK", ":LspTexlabCleanArtifacts<CR>", { silent = true }, { desc = "Cleaning files" })
vim.keymap.set("n", "FV", ":VimtexView<CR>", { silent = true }, { desc = "Viewing PDF" })
vim.keymap.set("n", "ff", ":Telescope fd<CR>")
vim.keymap.set("n", "fs", ":Telescope current_buffer_fuzzy_find<CR>")
vim.keymap.set("n", "fS", ":Telescope live_grep<CR>")
vim.keymap.set("n", "fk", ":Telescope resume<CR>")
vim.keymap.set("n", "fd", ":Telescope buffers<CR>")
vim.keymap.set("n", "<leader>u", ":Telescope undo<CR>", { desc = "Undo history" })
vim.keymap.set("n", "<leader>ff", ":Telescope<CR>", { desc = "Telescope functions"})
vim.keymap.set("n", "<leader>y", "<cmd>Telescope yank_history<CR>")
vim.keymap.set({"n", "x", "o" }, "s", require("flash").jump, { desc = "Flash" })
vim.keymap.set({"n", "x", "o" }, "S", require("flash").treesitter, { desc = "Flash Treesitter" })
vim.keymap.set("o", "r", require("flash").remote, { desc = "Remote Flash" })
vim.keymap.set({"o", "x" }, "R", require("flash").treesitter_search, { desc = "Treesitter Search" })
vim.keymap.set("c", "<C-s>", require("flash").toggle, { desc = "Toggle Flash Search" })

local manim_term
vim.keymap.set("n", "<leader>PP", function()
  vim.cmd("w")
  local file = vim.fn.expand("%")
  if not manim_term or not vim.api.nvim_buf_is_valid(manim_term) then
    vim.cmd("botright split")
    vim.cmd("resize 16")
    vim.cmd("terminal")
    manim_term = vim.api.nvim_get_current_buf()
  end
  vim.fn.chansend(vim.b.terminal_job_id, "manim -pqh " .. file .. "\n")
  vim.cmd("wincmd p")
end)

vim.cmd[[highlight Normal guibg=none ctermbg=none]]

vim.api.nvim_set_hl(0, "SpellBad",         { undercurl = true, sp = "#cc8080", bg = "NONE", })
vim.api.nvim_set_hl(0, "DiagnosticError",  { fg = "NONE", bg = "NONE", })
vim.api.nvim_set_hl(0, "DiagnosticWarn",   { fg = "NONE", bg = "NONE", })
vim.api.nvim_set_hl(0, "ErrorMsg",         { fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "WarningMsg",       { fg = "NONE", bg = "NONE", })
vim.api.nvim_set_hl(0, "NotifyERRORBody",  { fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "NotifyERRORTitle", { fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "MsgArea",          { bg = "NONE" })
vim.api.nvim_set_hl(0, "MsgSeparator",     { bg = "NONE" })
vim.api.nvim_set_hl(0, "Pmenu",            { bg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuSel",         { bg = "#777777" })
vim.api.nvim_set_hl(0, "PmenuSbar",        { bg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuThumb",       { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalFloat",      { bg = "NONE" })
vim.api.nvim_set_hl(0, "FloatBorder",      { bg = "NONE" })
